name: PyInstaller Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with the desired Python version

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller main.py

      - name: Commit changes
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"
          git add .
          git commit -m "Add PyInstaller workflow output" --author="Your Name <youremail@example.com>"
          git push
